### ISSUE TITLE
Informações da matérias não estão sendo recuperados

### ISSUE THREAD

**Issue by M3nin0** [filipemeneses/fatec-api#12]
Ao realizar testes com a API no momento de recuperar algumas informações das matérias, elas não  são recuperadas. Tentei usar métodos diferentes que recuperar informações de matéria, no caso testei o **getSchedules()** e **getAcademicCalendar()**, e nestes dois casos o nome das matérias não retorna, talvez haja alguma mudança no site, porque os métodos recuperam a sigla normal.

Mesmo que eu tenha feito o teste apenas para recuperar o nome segue um print do retorno do **getSchedules()** 

http://prntscr.com/i657kd

**Comment by filipemeneses** [comment]
Use o `getEnrolledDisciplines()` para resgatar a maioria dos dados da disciplina. `getSchedules()` não retorna todo o conteúdo porque extrai de uma página que só contém o código e a turma, se fosse para retornar com todas as informações, seria necessário fazer outra requisição. E no `getAcademicCalendar()` não tem disciplina mesmo, é uma lista de eventos/feriados.

Hmm, poderia adicionar esses dados com um request a mais, só iria custar uns ms

**Comment by M3nin0** [comment]
Beleza! Acho que seria bacana descrever isso na documentação. Existem outros métodos que fazem a busca de todos os dados ? Porque eu registrando eles insiro na documentação.

**Comment by filipemeneses** [comment]
Para disciplina, só o `getEnrolledDisciplines()` mesmo. É a tela do SIGA com mais dados. Pensando em adicionar um método para preencher a disciplina caso não encontre todos os dados na página

**Comment by M3nin0** [comment]
Boa, acho que ai evita exibições sem dado algum mas para os demais dados existe algum método que faça algo parecido com o <code>getEnrolledDisciplines()</code> ?

**Comment by filipemeneses** [comment]
Mapeei os métodos para ver o que retornam nas `Discipline`:

  | approved | absenses | classHours | classroomCode | classroomId | code | courseId | frequency | grade | name | periodId | presences | period | quitDate | state | teacherId | teacherName
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
getSchoolGrade |   |   | ✔ |   |   | ✔ |   | ✔ | ✔ | ✔ |   |   | ✔ |   | ✔ |   |  
getHistory | ✔ | ✔ |   |   |   | ✔ |   | ✔ | ✔ | ✔ |   |   | ✔ |   | ✔ |   |  
getSchedules |   |   | ✔ |   |   | ✔ |   |   |   |   |   |   |   |   |   |   |  
getPartialGrades |   |   |   |   | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ | ✔ |   |   | ✔ | ✔ | ✔ |  
getEnrolledDisciplines |   | ✔ |   | ✔ | ✔ | ✔ | ✔ |   |   | ✔ | ✔ | ✔ |   |   |   | ✔ | ✔

Retornar uma disciplina completa pelo *Account* custaria 4 requests a mais. Hm, outro detalhe é que as instâncias não compartilham os dados. Se você chamar o `getSchedules()` e `getHistory()` eles podem retornar as mesmas disciplinas, porém como instâncias diferentes.

**Comment by M3nin0** [comment]
Caraca, legal, bom saber que eles não compartilham informações, ai já fica claro o que armazenar. Vou fazer os testes nestes métodos, valeu =D

**Comment by filipemeneses** [comment]
Vou alterar a API para eles compartilharem informações, depois aproveitar e criar um método para carregar o perfil completo para depois usar qualquer método do [Student](https://filipemeneses.gitbooks.io/fatec-api/content/pt/methods/student.html) para pegar os dados. Algo assim:

```js
// loadProfile() faz todas as requisições possíveis, demora mais, mas retorna tudo:
Account.loadProfile().then(() => {
  // depois os dados estarão salvos na instância Account.student:
  Account.student.getEnrolledDisciplines()
  // <- [Discipline, Discipline]
})
```

**Comment by M3nin0** [comment]
A sim, fica mais fácil, inclusive, quando estava testando a API, tem um exemplo na documentação:

```js
const fatecApi = require('fatec-api')
const minhaConta = new fatecApi.Account('LOGIN', 'PASSWORD')

minhaConta.getName().then(nome => {
  console.log(nome)
  // <- 'SEU NOME COM CAPSLOCK'
})
```
Os dados raspados estão disponíveis em Account.student, continuando o exemplo::
```js
minhaConta.student.getName()
```

Nesse exemplo ao tentar utilizar o student não consegui recuperar as informações, talvez seja por eles não compartilharem, tentei usando o <code>login</code> e alguns outros e mesmo assim esse e os outros métodos do student não retornaram nada

**Comment by M3nin0** [comment]
Na parta da documentação acho bacana escrever um descritivo simples sobre cada classe, porque ai a documentação fica mais coesa, e no caso dos métodos o nome já explica eles.

Ainda sobre as classes, todas elas com exceção do **Student** e do **Account** são apenas estruturas para armazenar dados ?

Outra dúvida também é sobre os <code>set</code>, usando ele faço algum <code>POST</code> para o SIGA ? Ou é só para informação local ?

**Comment by filipemeneses** [comment]
Hmm, que estranho, não devia acontecer isso. Fiz um teste com este código com fatec-api@1.0.0:

```js
const minhaConta = new fatecApi.Account('LOGIN', 'SENHA')

minhaConta.getName().then(nome => {
  console.log(minhaConta.student.getName())
  // <- 'SEU NOME COM CAPSLOCK'
})

```

e consegui resgatar usando o método do `student`

**Comment by M3nin0** [comment]
Este código retorna, porém o <code>minhaConta.student.getName()</code> não, digo isso porque na documentação tem um exeplo com este método do **Student**.

**Comment by filipemeneses** [comment]
Todas as classes com exceção do *Student* e da *Account* são só para armazenar mesmo, setters e getters.

A *Account* não tem setters e todos os métodos `get` dela são requisições.
A *Student* não requisita nada e tem setters e getters.

------

No exemplo que dei, eu uso o `minhaConta.student.getName()`. Veja só: https://cl.ly/1I1Q2M2W3h3z

**Comment by M3nin0** [comment]
Beleza, pelo que entendi então para usar o student, vou ter que estar na promise ? Correto ? Porque fiz os testes na seguinte ordem:

```js
minhaConta.getName().then(nome => {
 console.log(nome);
})

minhaConta.student.getName();
```

Ai da forma que fiz então não funciona mesmo ?

**Comment by filipemeneses** [comment]
Aah, entendi a confusão. haha. Na documentação está em um bloco de código, como fosse em outra parte do código em outro momento depois da Promise completar.

O correto é usar:
```
minhaConta.getName().then(nome => {
  minhaConta.student.getName();
  console.log(nome);
})
```

Se usar `minhaConta.student.getName();` logo depois de `minhaConta.getName()`, vai receber `undefined`, a Promise `minhaConta.getName()` não resolve instantaneamente.

> Lembrando que todos os métodos da *Account* são requisições no SIGA, portanto Promises.

**Comment by M3nin0** [comment]
A então beleza, é que estava pensando que o **minhaConta** armazenava as informações no Student, e que eu pudesse requisitar sempre.

**Comment by filipemeneses** [comment]
*minhaConta* armazena as informações no Student, depois de ter requisitado no SIGA e tratado os dados.

**Comment by M3nin0** [comment]
oks, agora ficou mais claro haha
