### ISSUE TITLE
Problemas na API

### ISSUE THREAD

**Issue by weesleycabral** [filipemeneses/fatec-api#15]
Estou com problema na api, está dando esse erro: https://imgur.com/a/RhKsVOA
Alguém consegue me ajudar?

**Comment by filipemeneses** [comment]
Tem o trecho do código do `index.js`? Parece que deu alguma exceção de conexão ou falha de login

**Comment by weesleycabral** [comment]
https://imgur.com/a/C7025pU, sim no lugar de login e senha eu coloquei meu login e senha do siga, se puder me ajudar agradeço!

**Comment by weesleycabral** [comment]
Eu falei com você no privado do discord, se achar mais fácil responder por lá...
